import numpy as np

D = np.array([[1, 3], [2, 1]])
# print(D & 1)
A = np.array([[1, 1], [0, 1]])
b = np.array([5, 6])

# print((D & 1) @ A)
# print(((D >> 1) & 1) @ A)
# print(((D >> 2) & 1) @ A)
print(D & 1)
# print((D & 1) @ A + 2 * (((D >> 1) & 1) @ A) + 4 * (((D >> 2) & 1) @ A))
bits = np.stack([(D >> k) & 1 for k in range(1)], axis=2)
print(bits)
recovered = sum(bits[:,:,k] << k for k in range(bits.shape[2]))
print('hello')
print(bits.transpose(2,0,1))
print('result')
C= (bits.transpose(2,0,1) @ A).transpose(1,2,0)
print(C)
# C = np.matmul(bits.transpose(2,0,1), D).transpose(1,2,0)
recover_c = sum(C[:,:,k] << k for k in range(C.shape[2]))
print('bye')
# print(C)
print(recover_c)